"""
ProtoGenCore: AI Manufacturing Assistant
Generates manufacturing plans from product specifications.

Core capabilities:
- Spec intake: parse product requirements (dimensions, materials, tolerances, volume, finish)
- BOM generation: break product into components, recommend materials, estimate quantities
- Process planning: sequence manufacturing steps
- DFM analysis: flag manufacturability issues
- Cost estimation: calculate per-unit and tooling costs
- Supplier matching: recommend fabrication partners

Revenue: Freemium SaaS ($99/mo pro, $499/mo enterprise), API access ($0.10/call), referral fees (2-5%)

--- INVARIANTS (spec-invariance contract; one test each in tests/test_invariants.py) ---
P1  process() never raises; an invalid spec returns an error envelope with
    error_type, field, and timestamp.
P2  The CAD lifecycle composes: create_cad_workspace -> generate_cad_design ->
    export_cad_design yields exportable content.
P3  Export of an unknown design_id -> error envelope, never a crash.
P4  generate_cad_design validates dimensions_mm (a missing dimension is an
    error envelope, not an exception).
P5  describe().name == health().agent; capabilities are non-empty.
P6  process() is total: every dict input returns a dict with a "status" key.
"""

import logging
from dataclasses import dataclass, field
from datetime import datetime
from typing import Any, Dict, List, Optional
import math
import json

try:
    from . import validation
except ImportError:
    import validation

logger = logging.getLogger(__name__)


@dataclass
class ProductSpec:
    """Parsed product specification."""
    name: str
    description: str
    primary_material: str
    estimated_volume: int  # units
    target_dimensions: Optional[dict] = None  # {'height_mm': ..., 'width_mm': ..., 'length_mm': ...}
    tolerances: Optional[dict] = None  # {'general': '±0.1mm', ...}
    surface_finish: str = "raw"
    assembly_complexity: str = "moderate"
    lead_time_weeks: int = 12
    target_unit_cost: Optional[float] = None


@dataclass
class BOMLine:
    """Bill of Materials line item."""
    part_id: str
    description: str
    material: str
    quantity: float
    unit: str  # "pcs", "kg", "m", etc.
    unit_cost: float
    lead_time_days: int


@dataclass
class ManufacturingPlan:
    """Complete manufacturing plan."""
    spec_id: str
    product_name: str
    created_at: datetime
    bom: list  # of BOMLine
    process_sequence: list  # step descriptions
    dfm_issues: list  # DFM warnings
    cost_breakdown: dict
    supplier_recommendations: list
    feasibility_score: float


@dataclass
class ProcessStep:
    """A single manufacturing process step."""
    sequence: int
    process_type: str
    description: str
    equipment: str
    estimated_cost_per_unit: float
    setup_time_hours: float
    lead_time_days: int


class ProtoGenCore:
    """AI manufacturing planning assistant."""
    KNOWN_ACTIONS = frozenset({
        "create_cad_workspace", "generate_cad_design", "export_cad_design",
    })
    READ_ACTIONS = frozenset({"export_cad_design"})

    def __init__(self, config: Optional[dict] = None):
        self.config = config or {}
        self.logger = logger
        self.plans: dict = {}
        self.cad_workspaces: dict = {}
        self.cad_designs: dict = {}

    def create_cad_workspace(
        self,
        project_name: str,
        owner_agent: str,
        design_goal: str,
        constraints: Optional[Dict[str, Any]] = None,
    ) -> Dict[str, Any]:
        """
        Create a CAD design workspace that other agents can call through MCP.

        The workspace is a lightweight design environment contract: it tracks
        project intent, constraints, units, output formats, and subsequent CAD
        design artifacts generated by ProtoGen.
        """
        if not project_name or not isinstance(project_name, str):
            raise ValueError("project_name must be a non-empty string")
        if not owner_agent or not isinstance(owner_agent, str):
            raise ValueError("owner_agent must be a non-empty string")
        if not design_goal or not isinstance(design_goal, str):
            raise ValueError("design_goal must be a non-empty string")

        workspace_id = f"cad-{datetime.utcnow().strftime('%Y%m%d%H%M%S')}-{len(self.cad_workspaces) + 1}"
        workspace = {
            "workspace_id": workspace_id,
            "project_name": project_name,
            "owner_agent": owner_agent,
            "design_goal": design_goal,
            "constraints": constraints or {},
            "units": "mm",
            "environment": {
                "type": "parametric_cad_workspace",
                "supported_exports": ["openscad", "step_contract", "manufacturing_brief"],
                "cad_kernel_status": "script_contract_ready",
                "mcp_usable": True,
            },
            "design_ids": [],
            "created_at": datetime.utcnow().isoformat(),
        }
        self.cad_workspaces[workspace_id] = workspace
        return workspace

    def generate_cad_design(
        self,
        workspace_id: str,
        part_name: str,
        dimensions_mm: Dict[str, float],
        material: str = "aluminum",
        design_intent: str = "",
        features: Optional[List[Dict[str, Any]]] = None,
        output_formats: Optional[List[str]] = None,
    ) -> Dict[str, Any]:
        """
        Generate a parametric CAD design contract for a part.

        This creates a usable intermediate representation for other agents:
        dimensions, features, OpenSCAD-style script, manufacturability notes,
        and export metadata. It is intentionally deterministic so agents can
        call it repeatedly and compare outputs.
        """
        workspace = self.cad_workspaces.get(workspace_id)
        if workspace is None:
            raise ValueError(f"CAD workspace '{workspace_id}' not found")
        if not part_name or not isinstance(part_name, str):
            raise ValueError("part_name must be a non-empty string")

        clean_dims = self._validate_dimensions(dimensions_mm)
        features = features or []
        output_formats = output_formats or ["openscad", "manufacturing_brief"]

        design_id = f"design-{datetime.utcnow().strftime('%Y%m%d%H%M%S')}-{len(self.cad_designs) + 1}"
        cad_script = self._build_openscad_script(part_name, clean_dims, features)
        manufacturing_notes = self._cad_manufacturing_notes(clean_dims, material, features)

        design = {
            "design_id": design_id,
            "workspace_id": workspace_id,
            "part_name": part_name,
            "material": material,
            "design_intent": design_intent,
            "dimensions_mm": clean_dims,
            "features": features,
            "outputs": {
                "openscad": cad_script,
                "step_contract": {
                    "status": "contract_only",
                    "note": "Ready for handoff to a real CAD kernel/exporter.",
                    "units": "mm",
                },
                "manufacturing_brief": manufacturing_notes,
            },
            "requested_formats": output_formats,
            "created_at": datetime.utcnow().isoformat(),
        }
        self.cad_designs[design_id] = design
        workspace["design_ids"].append(design_id)
        return design

    def export_cad_design(self, design_id: str, export_format: str = "openscad") -> Dict[str, Any]:
        """Export a generated CAD design in a supported contract format."""
        design = self.cad_designs.get(design_id)
        if design is None:
            raise ValueError(f"CAD design '{design_id}' not found")
        outputs = design["outputs"]
        if export_format not in outputs:
            raise ValueError(f"Unsupported export_format '{export_format}'. Valid: {sorted(outputs)}")
        return {
            "status": "ok",
            "design_id": design_id,
            "export_format": export_format,
            "content": outputs[export_format],
            "timestamp": datetime.utcnow().isoformat(),
        }

    def _validate_dimensions(self, dimensions_mm: Dict[str, float]) -> Dict[str, float]:
        """Validate part dimensions and normalize to length/width/height in mm."""
        if not isinstance(dimensions_mm, dict):
            raise ValueError("dimensions_mm must be a dict")
        clean = {}
        for key in ("length", "width", "height"):
            value = dimensions_mm.get(key, dimensions_mm.get(f"{key}_mm"))
            if value is None:
                raise ValueError(f"dimensions_mm.{key} is required")
            if isinstance(value, bool) or not isinstance(value, (int, float)):
                # P4: strings like "40" must NOT coerce through the gate —
                # dimensions are numbers, not number-shaped text (N68 finding).
                raise ValueError(f"dimensions_mm.{key} must be numeric")
            value = float(value)
            if not math.isfinite(value) or value <= 0:
                raise ValueError(
                    f"dimensions_mm.{key} must be finite and > 0")
            clean[key] = value
        return clean

    def _build_openscad_script(
        self,
        part_name: str,
        dimensions_mm: Dict[str, float],
        features: List[Dict[str, Any]],
    ) -> str:
        """Build a deterministic OpenSCAD-style parametric script."""
        length = dimensions_mm["length"]
        width = dimensions_mm["width"]
        height = dimensions_mm["height"]
        lines = [
            f"// ProtoGen CAD contract: {part_name}",
            "// Units: millimeters",
            f"length = {length:.4f};",
            f"width = {width:.4f};",
            f"height = {height:.4f};",
            "",
            "module part() {",
            "  difference() {",
            "    cube([length, width, height], center=true);",
        ]
        for feature in features:
            if feature.get("type") == "through_hole":
                x = float(feature.get("x_mm", 0.0))
                y = float(feature.get("y_mm", 0.0))
                diameter = float(feature.get("diameter_mm", 5.0))
                lines.append(
                    f"    translate([{x:.4f}, {y:.4f}, 0]) "
                    f"cylinder(h=height + 2, d={diameter:.4f}, center=true, $fn=48);"
                )
        lines.extend([
            "  }",
            "}",
            "",
            "part();",
        ])
        return "\n".join(lines)

    def _cad_manufacturing_notes(
        self,
        dimensions_mm: Dict[str, float],
        material: str,
        features: List[Dict[str, Any]],
    ) -> Dict[str, Any]:
        """Create lightweight manufacturability guidance for the CAD contract."""
        max_dim = max(dimensions_mm.values())
        min_dim = min(dimensions_mm.values())
        issues = []
        if min_dim < 1.0:
            issues.append("Minimum dimension under 1mm may be fragile or hard to manufacture.")
        if max_dim > 500:
            issues.append("Largest dimension exceeds 500mm; confirm machine envelope and shipping constraints.")
        for feature in features:
            if feature.get("type") == "through_hole" and float(feature.get("diameter_mm", 0)) < 2:
                issues.append("Through-hole below 2mm may require small tooling or alternate process.")
        return {
            "material": material,
            "recommended_process": "cnc_machining" if material in ("aluminum", "steel", "titanium") else "3d_printing",
            "volume_mm3": dimensions_mm["length"] * dimensions_mm["width"] * dimensions_mm["height"],
            "feature_count": len(features),
            "issues": issues,
            "next_steps": [
                "Review dimensions against real part requirements.",
                "Send OpenSCAD contract to CAD kernel or human CAD operator for final geometry.",
                "Run DFM and cost estimate before quoting or manufacturing.",
            ],
        }

    async def process(self, input_data: dict) -> dict:
        """Main entry point: intake spec and generate manufacturing plan."""
        # Fleet-standard non-dict guard (N54 idiom): return the canonical
        # structured envelope instead of relying on the generic except below,
        # which produced a misleading raw AttributeError message.
        if not isinstance(input_data, dict):
            return {
                "status": "error",
                "error_type": "ValidationError",
                "field": "input_data",
                "value": type(input_data).__name__,
                "constraint": "input_data must be a dict",
                "message": (
                    "input_data must be a dict, got "
                    f"{type(input_data).__name__}"
                ),
                "timestamp": datetime.utcnow().isoformat(),
            }
        try:
            action = input_data.get("action") if isinstance(input_data, dict) else None
            if action == "create_cad_workspace":
                return {
                    "status": "success",
                    "workspace": self.create_cad_workspace(
                        project_name=input_data.get("project_name", ""),
                        owner_agent=input_data.get("owner_agent", ""),
                        design_goal=input_data.get("design_goal", ""),
                        constraints=input_data.get("constraints", {}),
                    ),
                    "timestamp": datetime.utcnow().isoformat(),
                }
            if action == "generate_cad_design":
                return {
                    "status": "success",
                    "design": self.generate_cad_design(
                        workspace_id=input_data.get("workspace_id", ""),
                        part_name=input_data.get("part_name", ""),
                        dimensions_mm=input_data.get("dimensions_mm", {}),
                        material=input_data.get("material", "aluminum"),
                        design_intent=input_data.get("design_intent", ""),
                        features=input_data.get("features", []),
                        output_formats=input_data.get("output_formats"),
                    ),
                    "timestamp": datetime.utcnow().isoformat(),
                }
            if action == "export_cad_design":
                return {
                    "status": "success",
                    "export": self.export_cad_design(
                        design_id=input_data.get("design_id", ""),
                        export_format=input_data.get("export_format", "openscad"),
                    ),
                    "timestamp": datetime.utcnow().isoformat(),
                }

            # Validate input before parsing
            try:
                validation.validate_process_input(input_data)
            except validation.ValidationError as ve:
                return {
                    "status": "error",
                    "field": ve.field,
                    "message": ve.message,
                    "error_type": ve.error_type,
                    "timestamp": datetime.utcnow().isoformat(),
                }
            
            spec = self._parse_spec(input_data)
            plan = self._generate_plan(spec)
            return {
                "status": "success",
                "plan": self._serialize_plan(plan),
                "timestamp": datetime.utcnow().isoformat(),
            }
        except Exception as e:
            self.logger.error(f"Plan generation failed: {e}")
            # N68: canonical error envelope for the flagship CAD paths too.
            # The CAD actions dispatch before the legacy validation gate, so
            # their ValueErrors used to surface here as a bare
            # {status, message} pair — violating the AGENT.md Output
            # Contract (harness error taxonomy + timestamp). Classify
            # ValueError/TypeError as ValidationError (input-shape faults
            # raised by generate_cad_design/export_cad_design validators),
            # everything else as RuntimeError. Additive fields only.
            error_type = (
                "ValidationError"
                if isinstance(e, (ValueError, TypeError, KeyError))
                else "RuntimeError"
            )
            return {
                "status": "error",
                "error_type": error_type,
                "message": str(e),
                "timestamp": datetime.utcnow().isoformat(),
            }

    def _parse_spec(self, input_data: dict) -> ProductSpec:
        """Parse and validate product specification."""
        required = ["name", "description", "primary_material", "estimated_volume"]
        if not all(k in input_data for k in required):
            raise ValueError(f"Missing required fields: {required}")

        return ProductSpec(
            name=input_data["name"],
            description=input_data["description"],
            primary_material=input_data["primary_material"].lower(),
            estimated_volume=int(input_data["estimated_volume"]),
            target_dimensions=input_data.get("target_dimensions", {}),
            tolerances=input_data.get("tolerances", {"general": "±0.1mm"}),
            surface_finish=input_data.get("surface_finish", "raw"),
            assembly_complexity=input_data.get("assembly_complexity", "moderate"),
            lead_time_weeks=input_data.get("lead_time_weeks", 12),
            target_unit_cost=input_data.get("target_unit_cost"),
        )

    def _generate_plan(self, spec: ProductSpec) -> ManufacturingPlan:
        """Generate comprehensive manufacturing plan."""
        plan_id = f"proto-{datetime.utcnow().strftime('%Y%m%d%H%M%S')}"

        # Generate BOM
        bom = self._generate_bom(spec)

        # Select processes
        process_sequence = self._select_processes(spec)

        # DFM analysis
        dfm_issues = self._perform_dfm_analysis(spec, process_sequence)

        # Cost breakdown
        cost_breakdown = self._calculate_costs(spec, bom, process_sequence)

        # Supplier recommendations
        suppliers = self._recommend_suppliers(spec, bom)

        # Feasibility score
        feasibility = self._score_feasibility(spec, cost_breakdown, dfm_issues)

        return ManufacturingPlan(
            spec_id=plan_id,
            product_name=spec.name,
            created_at=datetime.utcnow(),
            bom=bom,
            process_sequence=process_sequence,
            dfm_issues=dfm_issues,
            cost_breakdown=cost_breakdown,
            supplier_recommendations=suppliers,
            feasibility_score=feasibility,
        )

    def _generate_bom(self, spec: ProductSpec) -> list:
        """Generate bill of materials."""
        bom = []
        bom.append(BOMLine(
            part_id="MAIN_001",
            description=f"Primary {spec.primary_material} component",
            material=spec.primary_material,
            quantity=1.0,
            unit="pcs",
            unit_cost=50.0,
            lead_time_days=14,
        ))
        if spec.assembly_complexity in ("complex", "very_complex"):
            bom.append(BOMLine(
                part_id="FAST_001",
                description="Stainless steel fasteners",
                material="steel",
                quantity=12.0,
                unit="pcs",
                unit_cost=0.5,
                lead_time_days=5,
            ))
            bom.append(BOMLine(
                part_id="CONN_001",
                description="Electrical connectors",
                material="copper",
                quantity=4.0,
                unit="pcs",
                unit_cost=2.0,
                lead_time_days=7,
            ))
        return bom

    def _select_processes(self, spec: ProductSpec) -> list:
        """Select manufacturing processes and return ProcessStep objects."""
        processes = []
        seq = 1
        mat = spec.primary_material
        vol = spec.estimated_volume

        if mat in ("plastic_abs", "plastic_pla", "plastic_nylon"):
            if vol >= 10000:
                processes.append(ProcessStep(
                    sequence=seq, process_type="injection_molding",
                    description="Injection molding for high-volume plastic",
                    equipment="injection_mold", estimated_cost_per_unit=2.0,
                    setup_time_hours=8, lead_time_days=21,
                ))
            else:
                processes.append(ProcessStep(
                    sequence=seq, process_type="3d_printing",
                    description="FDM 3D printing for low-volume plastic",
                    equipment="fdm_printer", estimated_cost_per_unit=10.0,
                    setup_time_hours=1, lead_time_days=3,
                ))
            seq += 1
        elif mat in ("steel", "aluminum", "titanium"):
            processes.append(ProcessStep(
                sequence=seq, process_type="cnc_machining",
                description="CNC machining for metal component",
                equipment="cnc_mill", estimated_cost_per_unit=25.0,
                setup_time_hours=4, lead_time_days=5,
            ))
            seq += 1

        if spec.surface_finish != "raw":
            processes.append(ProcessStep(
                sequence=seq, process_type=f"surface_{spec.surface_finish}",
                description=f"Surface treatment: {spec.surface_finish}",
                equipment="surface_treatment", estimated_cost_per_unit=5.0,
                setup_time_hours=1, lead_time_days=3,
            ))
            seq += 1

        if spec.assembly_complexity in ("complex", "very_complex"):
            processes.append(ProcessStep(
                sequence=seq, process_type="assembly_testing",
                description="Final assembly and QA testing",
                equipment="assembly_line", estimated_cost_per_unit=15.0,
                setup_time_hours=2, lead_time_days=7,
            ))
        return processes

    def _perform_dfm_analysis(self, spec: ProductSpec, processes: list) -> list:
        """Perform design-for-manufacturability analysis."""
        issues = []
        if spec.estimated_volume > 1_000_000:
            issues.append("Ultra-high volume may require custom tooling (cost analysis recommended)")
        if spec.primary_material == "titanium":
            issues.append("Titanium requires specialized equipment and expertise (supplier constraints)")
        # Tolerance check
        if spec.tolerances:
            for k, v in spec.tolerances.items():
                tol_str = str(v)
                try:
                    tol_val = float(tol_str.replace("±", "").replace("mm", "").strip())
                    if tol_val < 0.05:
                        issues.append(f"Tight tolerance {v} on {k} requires precision machining (cost impact)")
                except ValueError:
                    pass
        # Volume-mismatch check: injection molding at low volume is uneconomical
        for p in processes:
            process_type = p.process_type if isinstance(p, ProcessStep) else p.get("process", "")
            if "injection_molding" in str(process_type) and spec.estimated_volume < 1000:
                issues.append(
                    f"Volume mismatch: injection molding requires high volume "
                    f"(current: {spec.estimated_volume} units, min recommended: 1000)"
                )
        return issues

    def _calculate_costs(self, spec: ProductSpec, bom: list, processes: list) -> dict:
        """Calculate full cost breakdown."""
        material_cost = sum(line.unit_cost * line.quantity for line in bom)
        labor_cost = sum(
            (p.estimated_cost_per_unit if isinstance(p, ProcessStep) else 50)
            for p in processes
        )
        tooling_raw = 5000 if spec.estimated_volume > 10000 else 0
        tooling_amortization = round(tooling_raw / max(spec.estimated_volume, 1), 4)
        subtotal = round(material_cost + labor_cost + tooling_amortization, 4)
        overhead = round(subtotal * 0.15, 4)
        profit_margin = round((subtotal + overhead) * 0.20, 4)
        selling_price = round(subtotal + overhead + profit_margin, 4)
        return {
            "material_cost": material_cost,
            "labor_cost": labor_cost,
            "tooling_amortization": tooling_amortization,
            "subtotal_manufacturing": subtotal,
            "overhead": overhead,
            "profit_margin": profit_margin,
            "selling_price_per_unit": selling_price,
        }

    def _recommend_suppliers(self, spec: ProductSpec, bom: list) -> dict:
        """Recommend suppliers grouped by category."""
        return {
            "materials": [
                {"name": "TechFab Industries", "specialty": spec.primary_material,
                 "rating": 4.5, "lead_time_days": 14},
            ],
            "manufacturing": [
                {"name": "Precision Machining Co", "specialty": "CNC",
                 "rating": 4.7, "lead_time_days": 10},
            ],
            "assembly": [
                {"name": "FlexAssembly Inc", "specialty": "electronics assembly",
                 "rating": 4.3, "lead_time_days": 7},
            ],
        }

    def _score_feasibility(self, spec: ProductSpec, costs: dict, dfm_issues: list) -> float:
        """Score manufacturing feasibility (0-1)."""
        score = 1.0
        if dfm_issues:
            score -= 0.1 * len(dfm_issues)
        if costs.get("selling_price_per_unit", costs.get("total_per_unit", 0)) > (spec.target_unit_cost or 1000):
            score -= 0.2
        return max(0.0, score)

    def _serialize_plan(self, plan: ManufacturingPlan) -> dict:
        """Serialize manufacturing plan to dict."""
        return {
            "spec_id": plan.spec_id,
            "product_name": plan.product_name,
            "created_at": plan.created_at.isoformat(),
            "bom": [{"part_id": line.part_id, "description": line.description, "material": line.material,
                     "quantity": line.quantity, "unit": line.unit, "unit_cost": line.unit_cost}
                    for line in plan.bom],
            "process_sequence": plan.process_sequence,
            "dfm_issues": plan.dfm_issues,
            "cost_breakdown": plan.cost_breakdown,
            "supplier_recommendations": plan.supplier_recommendations,
            "feasibility_score": plan.feasibility_score,
        }

    def health(self) -> dict:
        """Health check."""
        return {
            "status": "ok",
            "agent": "protogen-agent",
            "version": "0.3.1",   # VC2: healthz must report the running version
            "timestamp": datetime.utcnow().isoformat(),
            "plans_generated": len(self.plans),
            "cad_workspaces": len(self.cad_workspaces),
            "cad_designs": len(self.cad_designs),
        }

    def describe(self) -> dict:
        """Agent self-description."""
        return {
            "name": "protogen-agent",
            "version": "0.3.1",
            "role": "Viridis revenue MCP CAD design environment and manufacturing planning assistant",
            "capabilities": [
                "cad_workspace_creation",
                "parametric_cad_generation",
                "cad_export_contracts",
                "spec_parsing",
                "bom_generation",
                "process_planning",
                "dfm_analysis",
                "cost_estimation",
            ],
        }
